version: '3.9'
services:
  db:
    container_name: postgres
    restart: always
    image: postgres

    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    
    networks:
      - 'shared-network'

    volumes:
      - data:/var/lib/postgresql/data
  server:
    container_name: ecommerce-bn
    restart: unless-stopped
    build: .
    ports: 
      - ${PORT}:${PORT}
    networks:
      - 'shared-network'
    depends_on:
      - db
volumes:
  data:

networks: 
  shared-network: 