import dotenv from "dotenv";

dotenv.config();

module.exports = {
    development:{
        PORT:process.env.PORT,
        DB_HOST:process.env.DB_HOST,
        DB_USERNAME:process.env.DB_USERNAME,
        DB_PASSWORD:process.env.DB_PASSWORD,
        DEV_DATABASE:process.env.DEV_DATABASE,
        DEV_DATABASE_URL:process.env.DEV_DATABASE_URL,
        SERVICE:process.env.SERVICE,
        JWT_SECRET:process.env.JWT_SECRET,
        REFRESH_TOKEN:process.env.REFRESH_TOKEN,
        GOOGLE_CLIENT_ID:process.env.GOOGLE_CLIENT_ID,
        GOOGLE_SECRET:process.env.GOOGLE_SECRET,
        EMAIL:process.env.EMAIL,
        EMAIL_PASSWORD:process.env.EMAIL_PASSWORD
    },
    test:{
        PORT:process.env.PORT,
        DB_HOST:process.env.DB_HOST,
        DB_USERNAME:process.env.DB_USERNAME,
        DB_PASSWORD:process.env.DB_PASSWORD,
        TEST_DATABASE:process.env.TEST_DATABASE,
        TEST_DATABASE_URL:process.env.TEST_DATABASE_URL,
        SERVICE:process.env.SERVICE,
        JWT_SECRET:process.env.JWT_SECRET,
        REFRESH_TOKEN:process.env.REFRESH_TOKEN,
        GOOGLE_CLIENT_ID:process.env.GOOGLE_CLIENT_ID,
        GOOGLE_SECRET:process.env.GOOGLE_SECRET,
        EMAIL:process.env.EMAIL,
        EMAIL_PASSWORD:process.env.EMAIL_PASSWORD
    },
    production:{
        PORT:process.env.PORT,
        DB_HOST:process.env.DB_HOST,
        DB_USERNAME:process.env.DB_USERNAME,
        DB_PASSWORD:process.env.DB_PASSWORD,
        PRODUCTION_DATABASE:process.env.PRODUCTION_DATABASE,
        PROD_DATABASE_URL:process.env.TEST_DATABASE_URL,
        SERVICE:process.env.SERVICE,
        JWT_SECRET:process.env.JWT_SECRET,
        REFRESH_TOKEN:process.env.REFRESH_TOKEN,
        GOOGLE_CLIENT_ID:process.env.GOOGLE_CLIENT_ID,
        GOOGLE_SECRET:process.env.GOOGLE_SECRET,
        EMAIL:process.env.EMAIL,
        EMAIL_PASSWORD:process.env.EMAIL_PASSWORD
    }
};