name: CI/CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - develop
  pull_request: 
    branches:
      - develop
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    env: 
      DB_HOST: ${{secrets.DB_HOST}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      TEST_DATABASE: ${{secrets.DB_TEST_DATABASE}}
      PORT: ${{secrets.PORT}}
    steps:
      - uses: actions/checkout@v1
      - name: 'Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - run: npm run coverage
  