name: Deploy to production

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
        cashe: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Build and deploy the app to production
      run: npm run build --if-present
    


